services:
  web-controller-api:
    image: "web-controller-api-v1"
    build:
      context: .
      dockerfile: WebControllerApi/Dockerfile
    container_name: my-api
    depends_on:
      - pg-sql-binh
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database1=Host=postgres;Port=5432;Database=test_db;Username=admin;Password=170116Abc

  web-minimal-api:
    image: "web-minimal-api-v1"
    build:
      context: .
      dockerfile: WebMinimalApiAOT/Dockerfile
    depends_on:
      pg-sql-binh:
        condition: service_healthy
    ports:
      - "5002:8080"
    networks:
      - my-network-1
  pg-sql-binh:
    image: postgres:16
    container_name: binh-dev-pgsql
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 170116Abc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - my-network-1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  my-network-1:
    driver: bridge
volumes:
  postgres_data_dev:
