apiVersion: apps/v1
kind: Deployment
metadata:
  name: binh-dotnet-app-template-deloyment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-controller-service # matching với những pod nào có app = ...
  template:
    metadata:
      labels:
        app: api-controller-service  # tạo label - app cho template này
    spec:
      containers:
      - name: api-controller-container
        image: web-controller-api-v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          
  