apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: pod
spec:
  containers:
    - name: api-controller-container
      image: web-controller-api-v1
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          protocol: TCP